### ISSUE TITLE
static content - header of static content is interfering with nav

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1305]
![image](https://f.cloud.github.com/assets/6330971/2431859/bd9ee0d4-ad47-11e3-8d3b-68cbf934f21c.png)

![image](https://f.cloud.github.com/assets/6330971/2431861/ccfc3298-ad47-11e3-9419-10bee51cfc95.png)

**Comment by barryclark** [comment]
Fixed by #1299

**Comment by mikefantini** [comment]
sorry didn't see that! was only looking in issues

**Comment by barryclark** [comment]
Great one to catch!

**Comment by mikefantini** [comment]
FYI this is still an issue on /campaigns and search results. Opened up issue #1311

**Comment by barryclark** [comment]
Great, that'll be a quick fix. Thanks.
