### ISSUE TITLE
Stuck with old cached assets after deploy

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4867]
```
Dave Furnes: hmm, some font issues on production post-deploy

[7:30 PM] Dave Furnes uploaded an image: cursive font 
Add Comment

[7:30 PM] Dave Furnes uploaded an image: social icons 
Add Comment

[7:31 PM] Dave Furnes: We did switch up where some fonts are hosted (served via URL on our CDN now, rather than included in the NPM package), but the icon fonts are still being packaged the same way

[7:31 PM] Dave Furnes: So not sure why that’s borked too... Anyone have any ideas if anything might have changed with CORS settings perhaps?

[7:33 PM] Sergii Tkachenko: Looking into it

[7:33 PM] Mike Fantini: @dave nothing looks weird to me on production on chrome logged in and logged out

[7:33 PM] Dave Furnes: Kk, thanks Sergii! Seems to be failing in different ways in different browsers.

[7:33 PM] Dave Furnes: Yeah, Chrome is a-okay. @fantini

[7:33 PM] Sergii Tkachenko: it’s good here, right? http://staging.beta.dosomething.org/campaigns/closed-campaign?source=node/1165
Closed Campaign
This is a test closed campaign. (56KB)


[7:34 PM] Sergii Tkachenko uploaded an image: chrome / mac / prod 
Add Comment

[7:34 PM] Sergii Tkachenko uploaded an image: chrome / mac / staging 
Add Comment

[7:34 PM] Dave Furnes: Yep. That second one is correct.

[7:35 PM] Dave Furnes: It looks like it might be caching an old version of the CSS file sometimes? I’m getting errors of it trying to load the included icon fonts from the wrong path.

[7:35 PM] Sergii Tkachenko: so looks like it fail in chrome

[7:35 PM] Sergii Tkachenko: ok

[7:35 PM] Sergii Tkachenko uploaded an image: Pasted image at 2015-08-19, 7:35 PM 
Add Comment

[7:36 PM] Dave Furnes: yep. it should be looking in `/assets/icons` rather than `/assets/fonts/icomoon`

[7:36 PM] Sergii Tkachenko: staging Request URL:https://www.dosomething.org/sites/default/files/fonts/covered-grace/CoveredGrace-Regular.woff

[7:37 PM] Sergii Tkachenko: hmhm

[7:37 PM] Dave Furnes: that’s correct

[7:40 PM] Sergii Tkachenko: so where should it be?

[7:41 PM] Dave Furnes: https://www.dosomething.org/sites/default/files/fonts/covered-grace/CoveredGrace-Regular.woff

[7:42 PM] Sergii Tkachenko: where is it set

[7:42 PM] Sergii Tkachenko: as i can see it’s loaded with modernizer.js

[7:43 PM] Dave Furnes: here’s the font definitions: https://github.com/DoSomething/forge/blob/dev/scss/_base/_fonts.scss

GitHub
DoSomething/forge
forge - Interface framework and pattern library for DoSomething.org.

[7:43 PM] Dave Furnes: fonts are not loaded with modernizr.

[7:43 PM] Dave Furnes: just normal `@font-face` declarations

[7:44 PM] Sergii Tkachenko: so the question is why is it looking for it at https://www.dosomething.org/profiles/dosomething/themes/dosomething/paraneue_dosomething/node_modules/@dosomething/forge/dist/assets/fonts/covered-grace/CoveredGrace-Regular.ttf

[7:44 PM] Dave Furnes: That’s where it was previously set to load from, before we moved the fonts out of the Github repo/NPM package and onto our CDN (due to legal stuffs).

[7:44 PM] Dave Furnes: So my hunch is that it’s still using an old version of the CSS file that’s getting cached in Fastly somehow?

[7:45 PM] Sergii Tkachenko: the asset version is v1.0.28

[7:45 PM] Sergii Tkachenko: https://jenkins.dosomething.org/job/Deploy-Production/38/console

[7:47 PM] Dave Furnes: it’s loading the correct version of forge `@dosomething/forge@6.5.2 node_modules/@dosomething/forge`

[7:48 PM] Sergii Tkachenko: ok

[7:48 PM] Sergii Tkachenko: @font-face{font-family:"CoveredGrace";src:url("../node_modules/@dosomething/forge/dist/assets/fonts/covered-grace/CoveredGrace-Regular.eot");src:url("../node_modules/@dosomething/forge/dist/assets/fonts/covered-grace/CoveredGrace-Regular.eot?#iefix")

[7:49 PM] Sergii Tkachenko: why it’s being replaced with ../node_modules?

[7:49 PM] Dave Furnes: That’s what it was loading previously (in `@dosomething/forge@6.5.1`)

[7:50 PM] Sergii Tkachenko: so the css is old, right?

[7:50 PM] Dave Furnes: yep, it seems to be

[7:54 PM] Sergii Tkachenko: forge is what we called neue earlier?

[7:54 PM] Dave Furnes: yep

[7:55 PM] Sergii Tkachenko:
dosomething@ip-10-100-35-12:/var/www/www.dosomething.org$ cat /var/www/www.dosomething.org/releases/20150819153637/lib/themes/dosomething/paraneue_dosomething/node_modules/@dosomething/forge/scss/_base/_fonts.scss
// Proxima Nova
@font-face {
  font-family: "Proxima Nova";
  font-weight: 400;
  src: url("https://www.dosomething.org/sites/default/files/fonts/proxima-nova/ProximaNova-Regular.eot”);

[7:56 PM] Sergii Tkachenko: looks good

[7:56 PM] Sergii Tkachenko: "@dosomething/forge": "~6.5.0",

[7:57 PM] Dave Furnes: yeah, it’s definitely pulling in the correct source

[7:57 PM] Sergii Tkachenko: @ /var/www/www.dosomething.org/releases/20150819153637/lib/themes/dosomething/paraneue_dosomething
├─┬ @dosomething/forge@6.5.2

[7:58 PM] Sergii Tkachenko: so it looks like css is good

[7:58 PM] Sergii Tkachenko:
url("https://www.dosomething.org/sites/default/files/fonts/covered-grace/CoveredGrace-Regular.woff”)


[7:58 PM] Sergii Tkachenko: then the one we have now is cache

[7:58 PM] Sergii Tkachenko: @sena: can we flush varnish?

[7:59 PM] Sergii Tkachenko: MD5 (app.min.css) = 3376dfa567101ab26609c3b90da838fa

[7:59 PM] Sergii Tkachenko: 05b103f7c62e4329f764b55fb1316950  dist/app.min.css

[8:01 PM] Sergii Tkachenko: the one served from web isn’t the same we have on server

[8:02 PM] Sena Heydari: @sergii: Yep, one sec

[8:02 PM] Sergii Tkachenko: @dave: btw: https://www.dosomething.org/profiles/dosomething/themes/dosomething/paraneue_dosomething/dist/app.min.css?1223123

[8:02 PM] Sergii Tkachenko: works

[8:02 PM] Sergii Tkachenko: so it is cache after all

[8:03 PM] Sergii Tkachenko: should we add release version to app.min.css?

[8:03 PM] Sergii Tkachenko: like https://www.dosomething.org/profiles/dosomething/themes/dosomething/paraneue_dosomething/dist/app.min.css?v=1.0.28

[8:03 PM] Sergii Tkachenko: @dave: ^ ?

[8:05 PM] Sergii Tkachenko: and it’s fixed

[8:05 PM] Sergii Tkachenko: thanks @sena!
```

cc @sheydari-ds @mikefantini @DFurnes

**Comment by sergiitk** [comment]
Resolved by clearing varnish cache. Suggested solution append assets version to the css path:
https://www.dosomething.org/profiles/dosomething/themes/dosomething/paraneue_dosomething/dist/app.min.css?v=1.0.28

**Comment by DFurnes** [comment]
That's a good idea. Does it still leave us open to having cached versions of other assets (like images) though?

I unfortunately can't remember what the issue with it was, but perhaps we should look into re-enabling the `Deploy-Assets` versioned assets folder task.

**Comment by DFurnes** [comment]
Going to re-title & re-open so we can discuss if a more permanent fix is needed!

**Comment by DFurnes** [comment]
Fantini just noted that fonts were still broken in his browser. The ol' **⌘⇧R** seemed to fix things, but this confirms that we'll need some sort of cache-buster in place to keep this from breaking as we deploy in the future.

**Comment by mikefantini** [comment]
@DFurnes @sergii-tkachenko lots of folks are still seeing this on production right now. is this something we can fix for today's deploy?

**Comment by sergiitk** [comment]
@DFurnes how about the thing I suggested above with the version postfix?

**Comment by DFurnes** [comment]
That seems like a good quick fix.

**Comment by mikefantini** [comment]
so @sergii-tkachenko @DFurnes sorry don't totally follow who the version postfix work is on, but can whoever is taking this on please self-assign this issue?

thanks

**Comment by sergiitk** [comment]
@DFurnes can you do the fix?

**Comment by DFurnes** [comment]
Added the fix in the above PR. A better long-term fix for this would be to set up [asset fingerprinting](http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark), so we can also invalidate caches on image assets without needlessly destroying cache each time we release.

**Comment by sergiitk** [comment]
Good idea @DFurnes. This is actually the way Drupal does it by default.

**Comment by angaither** [comment]
@DFurnes was the fix we created a fix we feel ok with, or do we still want to look into a more long term solution?

**Comment by DFurnes** [comment]
There's an improved fix open in #4936. It's blocked on a little bug in Forge, and some review/discussion with other people on the team. Definitely worth trying to wrap up during this milestone.

**Comment by DFurnes** [comment]
Oh, and this was fixed in #6321 since Webpack now generates fingerprinted assets.
